sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: listings
      - name: census_g01_nsw_lga
      - name: census_g02_nsw_lga
      - name: nsw_lga_code
      - name: nsw_lga_suburb